// <auto-generated />
using System;
using System.Collections.Generic;
using HRMS.Core.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Core.Postgres.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260623185309_AddPayrollFeature")]
    partial class AddPayrollFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttendanceFeature.Domain.AttendanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("BreakHours")
                        .HasColumnType("double precision");

                    b.Property<string>("ClockInMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IpValidated")
                        .HasColumnType("boolean");

                    b.Property<bool>("LocationVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("double precision");

                    b.Property<double>("ProductiveHours")
                        .HasColumnType("double precision");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("SelfieUrl")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ShiftEndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ShiftStartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalHours")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("IdentityFeature.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IdentityFeature.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LeaveFeature.Domain.LeaveBalance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Available")
                        .HasColumnType("integer");

                    b.Property<int>("CarriedForward")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Encashed")
                        .HasColumnType("integer");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Pending")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<int>("TotalAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveBalances", (string)null);
                });

            modelBuilder.Entity("LeaveFeature.Domain.LeaveRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ApproverComments")
                        .HasColumnType("text");

                    b.Property<string>("ApproverId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingEmployee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BuddyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OnboardingEmployees", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingMilestone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("OnboardingMilestones", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("OnboardingTasks", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingTrainingModuleRef", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("HasCertificate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("OnboardingTrainingModuleRefs", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.RelocationSupport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allowance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LocalBuddyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("RelocationStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SupportTickets")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TravelDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisaStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("RelocationSupports", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.TeamIntroduction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntroductionStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("TeamMemberName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("TeamIntroductions", (string)null);
                });

            modelBuilder.Entity("OnboardingFeature.Domain.WelcomeMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnboardingEmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OnboardingEmployeeId");

                    b.ToTable("WelcomeMessages", (string)null);
                });

            modelBuilder.Entity("AttendanceFeature.Domain.AttendanceRecord", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("AttendanceRecordId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("AttendanceRecordId");

                            b1.ToTable("AttendanceRecords");

                            b1.WithOwner()
                                .HasForeignKey("AttendanceRecordId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("IdentityFeature.Domain.Role", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("RoleId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("IdentityFeature.Domain.User", b =>
                {
                    b.HasOne("IdentityFeature.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Role");

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingEmployee", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("OnboardingEmployeeId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("OnboardingEmployeeId");

                            b1.ToTable("OnboardingEmployees");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingEmployeeId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingMilestone", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("OnboardingMilestoneId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("OnboardingMilestoneId");

                            b1.ToTable("OnboardingMilestones");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingMilestoneId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingTask", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("OnboardingTaskId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("OnboardingTaskId");

                            b1.ToTable("OnboardingTasks");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingTaskId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.OnboardingTrainingModuleRef", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("OnboardingTrainingModuleRefId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("OnboardingTrainingModuleRefId");

                            b1.ToTable("OnboardingTrainingModuleRefs");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingTrainingModuleRefId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.RelocationSupport", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("RelocationSupportId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("RelocationSupportId");

                            b1.ToTable("RelocationSupports");

                            b1.WithOwner()
                                .HasForeignKey("RelocationSupportId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.TeamIntroduction", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("TeamIntroductionId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("TeamIntroductionId");

                            b1.ToTable("TeamIntroductions");

                            b1.WithOwner()
                                .HasForeignKey("TeamIntroductionId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("OnboardingFeature.Domain.WelcomeMessage", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("WelcomeMessageId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("WelcomeMessageId");

                            b1.ToTable("WelcomeMessages");

                            b1.WithOwner()
                                .HasForeignKey("WelcomeMessageId");
                        });

                    b.Navigation("UserContext");
                });
#pragma warning restore 612, 618
        }
    }
}
