// <auto-generated />
using System;
using System.Collections.Generic;
using HRMS.Core.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Core.Postgres.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260623132810_InitialIdentityMigration")]
    partial class InitialIdentityMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityFeature.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IdentityFeature.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IdentityFeature.Domain.Role", b =>
                {
                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("RoleId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("UserContext");
                });

            modelBuilder.Entity("IdentityFeature.Domain.User", b =>
                {
                    b.HasOne("IdentityFeature.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HRMS.Shared.Domain.Entity.UserBase", "UserContext", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("CreatedByUserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByUserId")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByUserName")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ProfilePicture")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Role");

                    b.Navigation("UserContext");
                });
#pragma warning restore 612, 618
        }
    }
}
